export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const SCHEDULE_DATA = 'SCHEDULE_DATA';


export const MATCH = 'MATCH';
export const MATCH_SUCCESS = 'MATCH_SUCCESS';
export const MATCH_ERROR = 'MATCH_ERROR';

export const SCHEDULE = 'SCHEDULE';
export const SCHEDULE_SUCCESS = 'SCHEDULE_SUCCESS';
export const SCHEDULE_ERROR = 'SCHEDULE_ERROR';

export const RECENTMATCH = 'RECENTMATCH';
export const RECENTMATCH_SUCCESS = 'RECENTMATCH_SUCCESS';
export const RECENTMATCH_ERROR = 'RECENTMATCH_ERROR';

export const RECENTMATCHAPI = 'RECENTMATCHAPI';
export const RECENTMATCHAPI_SUCCESS = 'RECENTMATCHAPI_SUCCESS';
export const RECENTMATCHAPI_ERROR = 'RECENTMATCHAPI_ERROR';

export const GET_PLAYERS = 'GET_PLAYERS';
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYERS_ERROR = 'GET_PLAYERS_ERROR';

export const PLAYERINFO = 'PLAYERINFO';
export const PLAYERINFO_SUCCESS = 'PLAYERINFO_SUCCESS';
export const PLAYERINFO_ERROR = 'PLAYERINFO_ERROR';

export const MATCHFECTCH = 'MATCHFECTCH';
export const MATCHFECTCH_SUCCESS = 'MATCHFECTCH_SUCCESS';
export const MATCHFECTCH_ERROR = 'MATCHFECTCH_ERROR';
export const SEASONS = 'SEASONS';
export const SEASONS_SUCCESS = 'SEASONS_SUCCESS';
export const SEASONS_ERROR = 'SEASONS_ERROR';

export const SEASONS_ID = 'SEASONS_ID';
export const SEASONS_ID_SUCCESS = 'SEASONS_ID_SUCCESS';
export const SEASONS_ID_ERROR = 'SEASONS_ID_ERROR';

export const COUNTRYINFO = 'COUNTRYINFO';
/* export const COUNTRYINFO_SUCCESS = 'COUNTRYINFO_SUCCESS';
export const COUNTRYINFO_ERROR = 'COUNTRYINFO_ERROR';
 */

export const SESSION = 'SESSION';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_ERROR = 'SESSION_ERROR';

export const ALLMATCH = 'ALLMATCH';
export const ALLMATCH_SUCCESS = 'ALLMATCH_SUCCESS';
export const ALLMATCH_ERROR = 'ALLMATCH_ERROR';

export const BALLBYBALL = 'BALLBYBALL';
export const BALLBYBALL_SUCCESS = 'BALLBYBALL_SUCCESS';
export const BALLBYBALL_ERROR = 'BALLBYBALL_ERROR';

export const BALLBYBALL_LIVE = 'BALLBYBALL_LIVE';
export const BALLBYBALL_LIVE_SUCCESS = 'BALLBYBALL_LIVE_SUCCESS';
export const BALLBYBALL_LIVE_ERROR = 'BALLBYBALL_LIVE_ERROR';

export const NEWS = 'NEWS';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const NEWS_ERROR = 'NEWS_ERROR';

export const WAGON_WHEEL = 'WAGON_WHEEL';
export const WAGON_WHEEL_SUCCESS = 'WAGON_WHEEL_SUCCESS';
export const WAGON_WHEEL_ERROR = 'WAGON_WHEEL_ERROR';

export const ARCHIVES = 'ARCHIVES';
export const ARCHIVES_SUCCESS = 'ARCHIVES_SUCCESS';
export const ARCHIVES_ERROR = 'ARCHIVES_ERROR';

export const ALLSEASON = 'ALLSEASON';
export const ALLSEASON_SUCCESS = 'ALLSEASON_SUCCESS';
export const ALLSEASON_ERROR = 'ALLSEASON_ERROR';

export const TEAMSCHEDULE = 'TEAMSCHEDULE';
export const TEAMSCHEDULE_SUCCESS = 'TEAMSCHEDULE_SUCCESS';
export const TEAMSCHEDULE_ERROR = 'TEAMSCHEDULE_ERROR';

export const MFETCH = 'MFETCH';
export const MFETCH_SUCCESS = 'MFETCH_SUCCESS';
export const MFETCH_ERROR = 'MFETCH_ERROR';